name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        docker build . --file Dockerfile --tag ${{ vars.DOCKERHUB_REPO }}:$SHORT_SHA
        docker build . --file Dockerfile --tag ${{ vars.DOCKERHUB_REPO }}:latest

    - name: Push the Docker image to Docker Hub
      run: |
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        docker push ${{ vars.DOCKERHUB_REPO }}:$SHORT_SHA
        docker push ${{ vars.DOCKERHUB_REPO }}:latest
