name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        SHORT_SHA=${{ github.sha::7 }}
        docker build . --file Dockerfile --tag namtn6/mock-springboot-api:$SHORT_SHA
        docker build . --file Dockerfile --tag namtn6/mock-springboot-api:latest

    - name: Push the Docker image to Docker Hub
      run: |
        SHORT_SHA=${{ github.sha::7 }}
        docker push namtn6/mock-springboot-api:$SHORT_SHA
        docker push namtn6/mock-springboot
