name: Docker Image CI

on:
  push:
    branches:
      - develop  # Run on push to develop branch (for dev environment)
      - main     # Run on push to main branch (for prod environment)
  pull_request:
    branches:
      - develop  # Run on pull requests targeting the develop branch (for dev environment)
      - main     # Run on pull requests targeting the main branch (for prod environment

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Dynamically set the environment based on the branch (develop or main)
    environment: ${{ github.ref == 'refs/heads/develop' && 'dev' || 'prod' }} 

    steps:
    - uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        docker build . --file Dockerfile --tag ${{ vars.DOCKERHUB_REPO }}:$SHORT_SHA
        docker build . --file Dockerfile --tag ${{ vars.DOCKERHUB_REPO }}:latest

    - name: Push the Docker image to Docker Hub
      run: |
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        docker push ${{ vars.DOCKERHUB_REPO }}:$SHORT_SHA
        docker push ${{ vars.DOCKERHUB_REPO }}:latest
